### ISSUE TITLE
fatal error: mkeapi.h: No such file or directory, when running catkin_make for ros1 client build

### ISSUE THREAD

**Issue by nisshan-x** [MagikEyeInc/SDK#1]
I tried to build Magikeye ros1 client, but fatal error happened.

## Error message

```
[ 50%] Building CXX object mkeros/CMakeFiles/mkeros1_node.dir/src/mkeros1_node.cpp.o
In file included from /usr/local/include/mke/cli/client.h:29:0,
                 from /home/xxxx/catkin_ws/src/mkeros/src/publisher.h:20,
                 from /home/xxxx/catkin_ws/src/mkeros/src/mkeros1_node.cpp:30:
/usr/local/include/mke/cli/error.h:19:10: fatal error: mkeapi.h: No such file or directory
 #include <mkeapi.h>
          ^~~~~~~~~~
compilation terminated.
mkeros/CMakeFiles/mkeros1_node.dir/build.make:62: recipe for target 'mkeros/CMakeFiles/mkeros1_node.dir/src/mkeros1_node.cpp.o' failed
make[2]: *** [mkeros/CMakeFiles/mkeros1_node.dir/src/mkeros1_node.cpp.o] Error 1
CMakeFiles/Makefile2:509: recipe for target 'mkeros/CMakeFiles/mkeros1_node.dir/all' failed
make[1]: *** [mkeros/CMakeFiles/mkeros1_node.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed
```

## What I did:

1. Install MagikEye C++ lib

```
sudo apt update
sudo apt upgrade -y
sudo apt install build-essential git cmake libboost-all-dev
cd SDK/client/cpp/mkeclient
mkdir build
cd build/
cmake ..
make
sudo make install
```

2. Build ros1

```
source ~/.bashrc
cd catkin_ws/
source devel/setup.bash
cd src
rosdep install -i --from-paths ./
cd ..
catkin_make
```

3. Another thing I tried

mkeapi.h is missing, so I installed mkeapi but nothing changed...

```
cd SDK/mkeapi/
mkdir build
cd build/
cmake ..
make
sudo make install
```

Could you support to solve this issue? Thanks.

**Comment by nisshan-x** [comment]
I found mkeapi.h in `/usr/local/include/mke/api/`, so mkeclient installation has been succeeded. That means something wrong with path exists.

This is a workaround I have found.

1. Tempolary copy mkeapi.h from mkeapi to mkeclient
```
cd ~[blahblah]/SDK/client/cpp/mkeclient/src/mke
mkdir api
cp ~[blahblah]/SDK/mkeapi/include/mkeapi.h .
```

2. Overwite include on `SDK/client/cpp/mkeclient/src/mke/cli/error.h`

```
#include "../api/mkeapi.h"
// #include <mkeapi.h>
```

3. Build and install according to instruction.

4. Then I launched ros1 node.

```
roscore
```

```
roslaunch mkeros mkeros1_cpp.launch
```

Copying mkeapi.h is not good way to build. So I hope you fix this issue.

**Comment by nisshan-x** [comment]
I found this instruction. I rolled changes back and tried this catkin_make command, but the same error happened.

https://github.com/MagikEyeInc/SDK/tree/main/client/ros1/mkeros#dependencies

**Comment by jan-heller** [comment]
Dear Nishimoto-san, thank you for your interest in the Magik Eye technology!

The mkeros cmake build system should be able to find and use `libmkeclient` and `mkeapi.h` automatically. There should be no need to install them manually, as long as their source directories stay in the same place relative to each other, i.e., they have not been moved in the SDK directory structure.

The `mkeros1_node` ROS node compilation is based on the CMake build system and Catkin. Let’s suppose that the ROS distribution has been installed into the `${ROS_ROOT}` (e.g. `/opt/ros/noetic/`) directory and the mkeros1_node codebase resides in the `${MKEROS_ROOT}` ROS package of `${ROS1_WS}` (e.g. `/path/to/SDK/client/ros1/mkeros/`) ROS workspace. The following BASH commands will compile the `mkeros1_node` into the `${ROS1_WS}/build/` directory:
```
$ mkdir "${ROS1_WS}/build"
$ cd "${ROS1_WS}/build"
$ source ${ROS_ROOT}/setup.bash
$ catkin_make --pkg mkeros --source ..
```

Please let me know it this works for you.

All the best,
  Jan

**Comment by nisshan-x** [comment]
I understood. It worked fine.

Thank you!
