### ISSUE TITLE
frame name "Map" is not compatible with ROS1/2

### ISSUE THREAD

**Issue by nisshan-x** [MagikEyeInc/SDK#3]
I found small issue on publisher.h on ros1/2. Frame name "Map" of PointCloud2 is not compatible with ROS1/2. "map" is appropriate.

current code that is wrong
```
cloud.header.frame_id = "Map";
```

I propose the correct code.
```
cloud.header.frame_id = "map";
```

Files that should be applied

- SDK/client/ros1/mkeros/src/publisher.h
- SDK/client/ros2/mkeros2/src/publisher.h

**Comment by jan-heller** [comment]
Fixed by e4a3ac92a7ec5bf57978d15d43feb81b1f595653.
